# Generated by Django 4.1 on 2022-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('board', models.CharField(max_length=100)),
                ('stance', models.CharField(max_length=200)),
            ],
        ),
    ]
