# Generated by Django 4.1 on 2022-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stance',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
