# Generated by Django 4.1 on 2022-08-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDatabase', '0002_alter_student_board_alter_student_stance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shoe',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
