# Generated by Django 4.1 on 2022-08-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDatabase', '0004_student_bindingsizw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bindingSizw',
            new_name='bindingSize',
        ),
    ]
