# Generated by Django 4.1 on 2022-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDatabase', '0006_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shoe',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
