# Generated by Django 4.1 on 2022-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
                ('instructors', models.CharField(max_length=200)),
            ],
        ),
    ]
